/*
 * This file is generated by parrot must
 * DOCUMENT LIST:
 * parrot must: http://gitlab.alibaba-inc.com/parrot/parrot-tool-must
 * @halofe/global-locale: http://gitlab.alibaba-inc.com/parrot/global-locale
 * @halofe/global-string-format: http://gitlab.alibaba-inc.com/parrot/global-string-format
 */

// import stringFormat from '@halofe/global-string-format';
import dayjs from 'dayjs';
import strings from './strings';
let language = 'zh-cn'; // Current language，默认中文

let intl; // Instance of intl-universal. Create by provideIntl
/**
 * update instance of intl universal
 */
function updateLocale(locale: string) {
  language = locale;
  dayjs.locale(language || 'zh-cn'); // en zh-cn
}

export const format = (
  id: { id: string; defaultString?: string },
  variables: { [key: string]: string },
) => {
  const languageKey = language === 'zh-cn' ? 'zh-CN' : 'en-US';

  const template = strings[languageKey][id.id] || id.defaultString || '';
  const text = template.replace(
    /\{(\w+)\}/g,
    (match, key) => variables[key] || match,
  );
  return text;
};
/**
 * Format string by key
 * For example:
 * $i18n.get('jsx.home.title'),
 * $i18n.get({
 *    id: 'jsx.home.hello',
 *    defaultMessage: 'Hello {name}' // not required
 * },{
 *  name: 'Alice'
 * })
 * More syntax: https://formatjs.io/guides/message-syntax/
 * @param {string|object} id key or object
 * @param {object} variable variable for id
 * @return {string} format message
 */
function get(id, variable?) {
  if (!intl) updateLocale(language);

  if (typeof id === 'string') {
    return format(
      {
        id: id,
      },
      variable,
    );
  } else if (typeof id === 'object' && id.dm) {
    id.defaultMessage = id.dm;
  }
  return format(
    {
      id: id.id,
      defaultString: id.dm,
    },
    variable,
  );
}

export default {
  intl,
  get,
  updateLocale,
  language,
};
